parameters:
- name: tag
  displayName: tag
  type: string
  default: '0.0.1'
  values:
  - 'v0.38.154'
  - '0.0.1'
  - '1.0.0'


variables:
  - name: tag_name
    value: ${{ parameters.tag }}


pool:
  vmImage: 'Ubuntu-latest'

resources:
  repositories:
  - repository: canary-checker
    type: github
    name: flanksource/canary-checker
    ref: 'refs/tags/$(tag_name)'
    endpoint: edeediong

steps:
  - checkout: canary-checker
        
  
  - task: Bash@3
    displayName: Boiler Release Note 
    inputs:
      targetType: 'inline' 
      script: |
        echo "## Release Notes $(tag_name)" > $(Build.ArtifactStagingDirectory)/release-notes.md
        cd '$(System.DefaultWorkingDirectory)' && git log > log.txt
        Encoded="ID%20in%20"
        JiraID=$(cat log.txt | grep -Po '\w+-\d+' | sort | uniq | sed -z 's/\n/,/g;s/,$/\n/')
        URL="https://oldmutual.atlassian.net/issues/?jql=${Encoded}(${JiraID})"
        echo "- **Jira URL:** [Click Here to Access Jira URL]($URL)" >> $(Build.ArtifactStagingDirectory)/release-notes.md
        cat $(Build.ArtifactStagingDirectory)/release-notes.md

  - task: Bash@3
    displayName: Git Commit Messages
    inputs:
      targetType: 'inline' 
      script: |
        echo "## Commit History >> $(Build.ArtifactStagingDirectory)/release-notes.md
        git log --tags="$(tag_name)" --pretty="* **%s** (%an)" -i -E --grep="feat:|fix:" >> $(Build.ArtifactStagingDirectory)/release-notes.md

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'