parameters:
- name: Repo
  type: string
  values:
    - OIPA_DEV0BASE
    - OIPA_BOT
    - OIPA_MAL
    - OIPA_DEV_QA
    - OIPA_DEV_SANDBOX

- name: Branch
  type: string
  default: main

variables:
  - name: tag_name
    value: ${{ parameters.tag }}


pool:
  vmImage: 'Ubuntu-latest'

steps:
  - checkout: git://OIPA/Infrastructure
    fetchDepth: 1
  - checkout: git://OIPA/${{ parameters.Repo }}@${{ parameters.Branch }}
    fetchDepth: 1
        
  
  - task: Bash@3
    displayName: Boiler Release Note 
    inputs:
      targetType: 'inline' 
      script: |
        echo "## Release Notes $(tag_name)" > $(Build.ArtifactStagingDirectory)/release-notes.md
        cd '$(System.DefaultWorkingDirectory)' && git log > log.txt
        Encoded="ID%20in%20"
        JiraID=$(cat log.txt | grep -Po '\w+-\d+' | sort | uniq | sed -z 's/\n/,/g;s/,$/\n/')
        URL="https://oldmutual.atlassian.net/issues/?jql=${Encoded}(${JiraID})"
        echo "**Jira URL:** [Click Here to Access Jira URL]($URL)" > $(Build.ArtifactStagingDirectory)/release-notes.md
        echo "## Release Notes $(tag_name)" >> $(Build.ArtifactStagingDirectory)/release-notes.md
        cat $(Build.ArtifactStagingDirectory)/release-notes.md

  - task: Bash@3
    displayName: Git Commit Messages
    inputs:
      targetType: 'inline' 
      script: |
        echo "## Commit History" >> $(Build.ArtifactStagingDirectory)/release-notes.md
        cd '$(System.DefaultWorkingDirectory)' && git log --pretty="* **%s** (%an)" v0.38.153..$(tag_name) -i -E --grep="feat:|fix:" >> $(Build.ArtifactStagingDirectory)/release-notes.md

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'